"use strict"
var __createBinding =
	(this && this.__createBinding) ||
	(Object.create
		? function (o, m, k, k2) {
				if (k2 === undefined) k2 = k
				var desc = Object.getOwnPropertyDescriptor(m, k)
				if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
					desc = {
						enumerable: true,
						get: function () {
							return m[k]
						},
					}
				}
				Object.defineProperty(o, k2, desc)
			}
		: function (o, m, k, k2) {
				if (k2 === undefined) k2 = k
				o[k2] = m[k]
			})
var __setModuleDefault =
	(this && this.__setModuleDefault) ||
	(Object.create
		? function (o, v) {
				Object.defineProperty(o, "default", { enumerable: true, value: v })
			}
		: function (o, v) {
				o["default"] = v
			})
var __importStar =
	(this && this.__importStar) ||
	(function () {
		var ownKeys = function (o) {
			ownKeys =
				Object.getOwnPropertyNames ||
				function (o) {
					var ar = []
					for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k
					return ar
				}
			return ownKeys(o)
		}
		return function (mod) {
			if (mod && mod.__esModule) return mod
			var result = {}
			if (mod != null)
				for (var k = ownKeys(mod), i = 0; i < k.length; i++)
					if (k[i] !== "default") __createBinding(result, mod, k[i])
			__setModuleDefault(result, mod)
			return result
		}
	})()
Object.defineProperty(exports, "__esModule", { value: true })
// kilocode_change - new file
const vitest_1 = require("vitest")
const vscode = __importStar(require("vscode"))
const terminalCommandGenerator_1 = require("../terminalCommandGenerator")
const ContextProxy_1 = require("../../core/config/ContextProxy")
const single_completion_handler_1 = require("../single-completion-handler")
vitest_1.vi.mock("vscode")
vitest_1.vi.mock("../../core/config/ContextProxy")
vitest_1.vi.mock("../single-completion-handler")
vitest_1.vi.mock("../../shared/support-prompt", () => ({
	supportPrompt: {
		create: vitest_1.vi.fn().mockReturnValue("mocked prompt"),
	},
}))
vitest_1.vi.mock("../../core/config/ProviderSettingsManager", () => ({
	ProviderSettingsManager: vitest_1.vi.fn().mockImplementation(() => ({
		initialize: vitest_1.vi.fn().mockResolvedValue(undefined),
		getProfile: vitest_1.vi.fn().mockResolvedValue({
			name: "test",
			apiProvider: "anthropic",
			apiKey: "test-key",
		}),
	})),
}))
vitest_1.vi.mock("../../i18n", () => ({
	t: vitest_1.vi.fn((key, params) => {
		const translations = {
			"kilocode:terminalCommandGenerator.inputPrompt": "Kilo: Describe the command you want to generate",
			"kilocode:terminalCommandGenerator.inputPlaceholder":
				"e.g., kill the process running on port 3001, find large files, etc",
			"kilocode:terminalCommandGenerator.noActiveTerminal":
				"No active terminal found. Please open a terminal first.",
			"kilocode:terminalCommandGenerator.generatingProgress": "Generating terminal command...",
			"kilocode:terminalCommandGenerator.commandGenerated": `Generated command: ${params?.command || ""}`,
			"kilocode:terminalCommandGenerator.generationFailed": `Failed to generate command: ${params?.error || ""}`,
			"kilocode:terminalCommandGenerator.warningDialog.title": "Always Verify AI-Generated Commands",
			"kilocode:terminalCommandGenerator.warningDialog.message":
				"This command was generated by AI and may not be accurate. Terminal actions cannot be undone—once executed, changes are permanent. Running unverified commands can result in irreversible data loss, security issues, or system damage. Review and understand the command completely before proceeding!",
			"kilocode:terminalCommandGenerator.warningDialog.okButton": "OK, I Understand",
			"kilocode:terminalCommandGenerator.warningDialog.cancelButton": "Cancel",
		}
		return translations[key] || key
	}),
}))
;(0, vitest_1.describe)("generateTerminalCommand", () => {
	const mockOutputChannel = {
		appendLine: vitest_1.vi.fn(),
	}
	const mockContext = {
		subscriptions: [],
		workspaceState: {
			get: vitest_1.vi.fn(),
		},
		globalState: {
			get: vitest_1.vi.fn(),
			update: vitest_1.vi.fn().mockResolvedValue(undefined),
		},
	}
	const mockTerminal = {
		sendText: vitest_1.vi.fn(),
		show: vitest_1.vi.fn(),
		shellIntegration: {
			cwd: {
				fsPath: "/test/path",
			},
		},
	}
	;(0, vitest_1.beforeEach)(() => {
		vitest_1.vi.clearAllMocks()
		const mockContextProxy = {
			getProviderSettings: vitest_1.vi.fn().mockReturnValue({
				apiProvider: "anthropic",
				apiKey: "test-key",
			}),
			getValue: vitest_1.vi.fn().mockReturnValue(null),
		}
		Object.defineProperty(ContextProxy_1.ContextProxy, "instance", {
			get: vitest_1.vi.fn(() => mockContextProxy),
			configurable: true,
		})
		vscode.window.showInputBox = vitest_1.vi.fn().mockResolvedValue("list files")
		Object.defineProperty(vscode.window, "activeTerminal", {
			get: vitest_1.vi.fn(() => mockTerminal),
			configurable: true,
		})
		vscode.window.withProgress = vitest_1.vi.fn().mockImplementation(async (options, callback) => {
			const mockProgress = { report: vitest_1.vi.fn() }
			return await callback(mockProgress, {})
		})
		vscode.window.showInformationMessage = vitest_1.vi.fn().mockResolvedValue(undefined)
		vscode.window.showErrorMessage = vitest_1.vi.fn().mockResolvedValue(undefined)
		// Mock ProgressLocation enum
		Object.defineProperty(vscode, "ProgressLocation", {
			value: {
				Notification: 15,
				Window: 10,
				SourceControl: 1,
			},
			configurable: true,
		})
		vitest_1.vi.mocked(single_completion_handler_1.singleCompletionHandler).mockResolvedValue("ls -la")
	})
	;(0, vitest_1.it)("should generate and place terminal command without executing", async () => {
		// Mock returning user (warning already acknowledged)
		vitest_1.vi.mocked(mockContext.globalState.get).mockReturnValue(true)
		await (0, terminalCommandGenerator_1.generateTerminalCommand)({
			outputChannel: mockOutputChannel,
			context: mockContext,
		})
		;(0, vitest_1.expect)(vscode.window.showInputBox).toHaveBeenCalledWith({
			prompt: "Kilo: Describe the command you want to generate",
			placeHolder: "e.g., kill the process running on port 3001, find large files, etc",
			ignoreFocusOut: true,
		})
		;(0, vitest_1.expect)(single_completion_handler_1.singleCompletionHandler).toHaveBeenCalled()
		;(0, vitest_1.expect)(mockTerminal.sendText).toHaveBeenCalledWith("ls -la", false)
		;(0, vitest_1.expect)(mockTerminal.show).toHaveBeenCalled()
		;(0, vitest_1.expect)(vscode.window.showInformationMessage).toHaveBeenCalledWith("Generated command: ls -la")
	})
	;(0, vitest_1.it)("should handle user cancellation", async () => {
		// Mock returning user (warning already acknowledged)
		vitest_1.vi.mocked(mockContext.globalState.get).mockReturnValue(true)
		vscode.window.showInputBox = vitest_1.vi.fn().mockResolvedValue(undefined)
		await (0, terminalCommandGenerator_1.generateTerminalCommand)({
			outputChannel: mockOutputChannel,
			context: mockContext,
		})
		;(0, vitest_1.expect)(single_completion_handler_1.singleCompletionHandler).not.toHaveBeenCalled()
		;(0, vitest_1.expect)(mockTerminal.sendText).not.toHaveBeenCalled()
	})
	;(0, vitest_1.it)("should handle missing active terminal", async () => {
		// Mock returning user (warning already acknowledged)
		vitest_1.vi.mocked(mockContext.globalState.get).mockReturnValue(true)
		Object.defineProperty(vscode.window, "activeTerminal", {
			get: vitest_1.vi.fn(() => undefined),
			configurable: true,
		})
		await (0, terminalCommandGenerator_1.generateTerminalCommand)({
			outputChannel: mockOutputChannel,
			context: mockContext,
		})
		;(0, vitest_1.expect)(vscode.window.showErrorMessage).toHaveBeenCalledWith(
			"No active terminal found. Please open a terminal first.",
		)
		;(0, vitest_1.expect)(single_completion_handler_1.singleCompletionHandler).not.toHaveBeenCalled()
	})
	;(0, vitest_1.it)("should handle API configuration errors", async () => {
		// Mock returning user (warning already acknowledged)
		vitest_1.vi.mocked(mockContext.globalState.get).mockReturnValue(true)
		const mockContextProxy = {
			getProviderSettings: vitest_1.vi.fn().mockReturnValue(null),
			getValue: vitest_1.vi.fn().mockReturnValue([]),
		}
		Object.defineProperty(ContextProxy_1.ContextProxy, "instance", {
			get: vitest_1.vi.fn(() => mockContextProxy),
			configurable: true,
		})
		await (0, terminalCommandGenerator_1.generateTerminalCommand)({
			outputChannel: mockOutputChannel,
			context: mockContext,
		})
		;(0, vitest_1.expect)(vscode.window.showErrorMessage).toHaveBeenCalledWith(
			vitest_1.expect.stringContaining("Failed to generate command:"),
		)
	})
	;(0, vitest_1.describe)("warning dialog functionality", () => {
		;(0, vitest_1.it)("should show warning dialog on first use", async () => {
			// Mock first-time user (warning not acknowledged)
			vitest_1.vi.mocked(mockContext.globalState.get).mockReturnValue(false)
			vscode.window.showInformationMessage = vitest_1.vi.fn().mockResolvedValue("OK, I Understand")
			await (0, terminalCommandGenerator_1.generateTerminalCommand)({
				outputChannel: mockOutputChannel,
				context: mockContext,
			})
			;(0, vitest_1.expect)(vscode.window.showInformationMessage).toHaveBeenCalledWith(
				vitest_1.expect.stringContaining("Always Verify AI-Generated Commands"),
				vitest_1.expect.objectContaining({ modal: true }),
				"OK, I Understand",
				"Cancel",
			)
			;(0, vitest_1.expect)(mockContext.globalState.update).toHaveBeenCalledWith(
				"terminalCommandWarningAcknowledged",
				true,
			)
			;(0, vitest_1.expect)(mockTerminal.sendText).toHaveBeenCalledWith("ls -la", false)
		})
		;(0, vitest_1.it)("should not show warning dialog if already acknowledged", async () => {
			// Mock returning user (warning already acknowledged)
			vitest_1.vi.mocked(mockContext.globalState.get).mockReturnValue(true)
			await (0, terminalCommandGenerator_1.generateTerminalCommand)({
				outputChannel: mockOutputChannel,
				context: mockContext,
			})
			;(0, vitest_1.expect)(vscode.window.showInformationMessage).toHaveBeenCalledTimes(1) // Only the success message
			;(0, vitest_1.expect)(vscode.window.showInformationMessage).toHaveBeenCalledWith(
				"Generated command: ls -la",
			)
			;(0, vitest_1.expect)(mockContext.globalState.update).not.toHaveBeenCalledWith(
				"terminalCommandWarningAcknowledged",
				true,
			)
			;(0, vitest_1.expect)(mockTerminal.sendText).toHaveBeenCalledWith("ls -la", false)
		})
		;(0, vitest_1.it)("should abort command generation if user cancels warning dialog", async () => {
			// Mock first-time user who cancels the warning
			vitest_1.vi.mocked(mockContext.globalState.get).mockReturnValue(false)
			vscode.window.showInformationMessage = vitest_1.vi.fn().mockResolvedValue("Cancel")
			await (0, terminalCommandGenerator_1.generateTerminalCommand)({
				outputChannel: mockOutputChannel,
				context: mockContext,
			})
			;(0, vitest_1.expect)(vscode.window.showInformationMessage).toHaveBeenCalledWith(
				vitest_1.expect.stringContaining("Always Verify AI-Generated Commands"),
				vitest_1.expect.objectContaining({ modal: true }),
				"OK, I Understand",
				"Cancel",
			)
			;(0, vitest_1.expect)(mockContext.globalState.update).not.toHaveBeenCalledWith(
				"terminalCommandWarningAcknowledged",
				true,
			)
			;(0, vitest_1.expect)(vscode.window.showInputBox).not.toHaveBeenCalled()
			;(0, vitest_1.expect)(mockTerminal.sendText).not.toHaveBeenCalled()
		})
		;(0, vitest_1.it)("should abort command generation if user dismisses warning dialog", async () => {
			// Mock first-time user who dismisses the warning (returns undefined)
			vitest_1.vi.mocked(mockContext.globalState.get).mockReturnValue(false)
			vscode.window.showInformationMessage = vitest_1.vi.fn().mockResolvedValue(undefined)
			await (0, terminalCommandGenerator_1.generateTerminalCommand)({
				outputChannel: mockOutputChannel,
				context: mockContext,
			})
			;(0, vitest_1.expect)(vscode.window.showInformationMessage).toHaveBeenCalledWith(
				vitest_1.expect.stringContaining("Always Verify AI-Generated Commands"),
				vitest_1.expect.objectContaining({ modal: true }),
				"OK, I Understand",
				"Cancel",
			)
			;(0, vitest_1.expect)(mockContext.globalState.update).not.toHaveBeenCalledWith(
				"terminalCommandWarningAcknowledged",
				true,
			)
			;(0, vitest_1.expect)(vscode.window.showInputBox).not.toHaveBeenCalled()
			;(0, vitest_1.expect)(mockTerminal.sendText).not.toHaveBeenCalled()
		})
		;(0, vitest_1.it)("should handle globalState.get returning undefined (first-time user)", async () => {
			// Mock globalState.get returning undefined (equivalent to false for first-time user)
			vitest_1.vi.mocked(mockContext.globalState.get).mockReturnValue(undefined)
			vscode.window.showInformationMessage = vitest_1.vi.fn().mockResolvedValue("OK, I Understand")
			await (0, terminalCommandGenerator_1.generateTerminalCommand)({
				outputChannel: mockOutputChannel,
				context: mockContext,
			})
			;(0, vitest_1.expect)(vscode.window.showInformationMessage).toHaveBeenCalledWith(
				vitest_1.expect.stringContaining("Always Verify AI-Generated Commands"),
				vitest_1.expect.objectContaining({ modal: true }),
				"OK, I Understand",
				"Cancel",
			)
			;(0, vitest_1.expect)(mockContext.globalState.update).toHaveBeenCalledWith(
				"terminalCommandWarningAcknowledged",
				true,
			)
		})
	})
})
//# sourceMappingURL=terminalCommandGenerator.spec.js.map
